* A proposal for templatization of SPDX licenses.

** Introduction

Certain sections of a license vary as they are used. Some of this
variability is by design (think of the BSD family of licenses). In
other cases it is due to small changes in licenses as they are copied
and propagated.

** Rules

A variable section of a license is specified with a rule. A rule is
wrapped between {{}} and is composed of 5 parts. Each is separated with ;. They cannot be embedded within other rules.

- original: the original text of the rule. It should be the first field. It is required.
- match: a POSIX regular expression (semicolons are escaped with \; within it). This field is required.
- name: name of the field in the template. Each rule must have a name. This field is required.
- type: required or optional. This field is required.
- example: another example of the use of the text. This field is optional.

** Example:

#+BEGIN_EXAMPLE
{{original=THE AUTHOR OR CONTRIBUTORS;match=.+;name=copyrightHolderLiability;type=required;example=dmg inc.}}
#+END_EXAMPLE

This matches the regular expression _.+_ /"any character at least
once"/. It is /required/, its name is /copyrightHolderLiability/ and an example of the use of the rule is the text /THE AUTHOR OR CONTRIBUTORS/.



** Contact

Comments, patches, suggestions to Daniel German, dmg@uvic.ca


